### ISSUE TITLE
casestrategy报错

### ISSUE THREAD

**Issue by 100Continue** [pengchenglin/ATX-Test#6]
请问在执行 run_all_cases.py 时，报了以下错误，是不是有路径配置问题？

[I 210119 19:51:12 devices_new:145] 
    There has 2  USB devices alive 
Traceback (most recent call last):
  File "/Users/xxx/Documents/xxx/pythonWorkspaces/ATX-Test/Demo/run_all_cases.py", line 30, in <module>
    cases = cs.collect_cases(suite=True)
  File "/Users/xxx/Documents/xxx/pythonWorkspaces/ATX-Test/Public/casestrategy.py", line 40, in collect_cases
    self._collect_cases(cases, top_dir=test_suite)
  File "/Users/xxx/Documents/xxx/pythonWorkspaces/ATX-Test/Public/casestrategy.py", line 16, in _collect_cases
    suites = unittest.defaultTestLoader.discover(self.case_path, pattern=self.case_pattern, top_level_dir=top_dir)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 306, in discover
    os.path.dirname((the_module.__file__)))
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
['TestSuite_demo']
/Users/xxx/Documents/xxx/pythonWorkspaces/ATX-Test/Demo/TestCase

Process finished with exit code 1

**Comment by pengchenglin** [comment]
貌似是python3.8的问题   试试python3.6.8看看
